/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./../src/views/error/403.vue')['default']
    404: typeof import('./../src/views/error/404.vue')['default']
    505: typeof import('./../src/views/error/505.vue')['default']
    Animation: typeof import('./../src/components/animation.vue')['default']
    App: typeof import('./../src/App.vue')['default']
    Auth: typeof import('./../src/layouts/auth.vue')['default']
    BreadCrumbs: typeof import('./../src/components/BreadCrumbs.vue')['default']
    Captcha: typeof import('./../src/components/Captcha.vue')['default']
    Dashboard: typeof import('./../src/views/home/dashboard.vue')['default']
    Editor: typeof import('./../src/layouts/editor.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    Error: typeof import('./../src/layouts/error.vue')['default']
    Home: typeof import('./../src/layouts/home/home.vue')['default']
    LkButton: typeof import('./../src/components/From/lk-button.vue')['default']
    LkInput: typeof import('./../src/components/From/lk-input.vue')['default']
    Login: typeof import('./../src/views/auth/login.vue')['default']
    Mail: typeof import('./../src/views/member/mail.vue')['default']
    Markdown: typeof import('./../src/components/editor/markdown.vue')['default']
    Member: typeof import('./../src/layouts/member.vue')['default']
    Notification: typeof import('./../src/components/Notification.vue')['default']
    Register: typeof import('./../src/views/auth/register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestGuard: typeof import('./../src/views/auth/testGuard.vue')['default']
    TopBar: typeof import('./../src/components/Top/topBar.vue')['default']
    Validate: typeof import('./../src/views/auth/validate.vue')['default']
    WangEditor: typeof import('./../src/components/editor/wangEditor.vue')['default']
  }
}
